//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consulta()
        {
            this.DetalleConsulta = new HashSet<DetalleConsulta>();
        }
    
        public int IDConsulta { get; set; }
        public Nullable<int> IDProfesional { get; set; }
        public Nullable<int> IDMascota { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Peso { get; set; }
        public string Observación { get; set; }
    
        public virtual Mascota Mascota { get; set; }
        public virtual Profesional Profesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleConsulta> DetalleConsulta { get; set; }
    }
}
