//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleConsulta
    {
        public int IDDetalle { get; set; }
        public Nullable<int> IDConsulta { get; set; }
        public Nullable<int> IDTipoConsulta { get; set; }
        public string Diagnostico { get; set; }
        public string Tratamiento { get; set; }
        public string Dosis { get; set; }
        public Nullable<int> NumeroLote { get; set; }
        public Nullable<System.DateTime> FechaVto { get; set; }
    
        public virtual Consulta Consulta { get; set; }
        public virtual TipoConsulta TipoConsulta { get; set; }
    }
}
